# Matrices (Rank 2 Tensors) in NumPy

In [1]:
import numpy as np

In [51]:
# buat matrix X berukuran 2x3 menggunakan numpy
x = np.array ([[21,45,8],
                   [10,5, 90]])
x

array([[21, 45,  8],
       [10,  5, 90]])

In [3]:
# tampilkan ukuran dari matrix X
x. shape

(3, 2)

In [20]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
x [:,0]

array([21, 10])

In [42]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
x [1, :]

array([10,  5, 90])

# Matrices in PyTorch

In [ ]:
import torch

In [44]:
# buat matrix X berukuran 2x3 menggunakan pytorch
x_pt = torch.tensor([[21,45,8],
                   [10,5, 90]])
x_pt

tensor([[21, 45,  8],
        [10,  5, 90]])

In [40]:
# tampilkan ukuran dari matrix X
x_pt.shape

torch.Size([2, 3])

In [45]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
x_pt[0, :]

tensor([21, 45,  8])

In [46]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
x_pt[1, :]

tensor([10,  5, 90])

# *Matrices in TensorFlow*

In [73]:
import tensorflow as tf

In [74]:
# buat matrix X berukuran 2x3 menggunakan TensorFlow
x_tf = tf.Variable([[21,45,8],
                    [10,5,90]])
x_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[21, 45,  8],
       [10,  5, 90]], dtype=int32)>

In [75]:
# tampilkan ukuran dari matrix X
x_tf.shape

TensorShape([2, 3])

In [76]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
x_tf[0, :]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([21, 45,  8], dtype=int32)>

In [77]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
x_tf[1, :]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10,  5, 90], dtype=int32)>