In [23]:
import numpy as np

In [25]:
# buat vector x dengan ukuran 3x1
x = np.array([55, 2, 5])
x

array([55,  2,  5])

In [26]:
# hitung panjang vector x
len(x)

3

In [29]:
# tampilkan ukuran vector x
x.shape

(3,)

In [30]:
# tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [31]:
# akses elemen pertama dari vector x
x[0]


np.int64(55)

In [32]:
# tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.int64

In [33]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([55,  2,  5])

In [34]:
# tampilkan ukuran dari vector x_t
x_t.shape

(3,)

In [35]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([55, 2, 5])
y

array([55,  2,  5])

In [36]:
# tampilkan ukuran dari vector x_t
y.shape

(3,)

In [40]:
import torch
import tensorflow as tf



In [42]:
# lakukan soal nomor 2 menggunakan pytorch dan tensorflow
x_pt = torch.tensor([55, 2, 5])
x_t

array([55,  2,  5])